server:
  port: 8090

eureka:
  instance:
    hostname: localhost
    appname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  
management:
  security:
    enabled: false
    